<?php
/* 
 * Copyright (c) 2018-2021   All rights reserved.
 *
 * 创建时间：2021-11-25 11:03:06
 *
 * 项目：/ipban  -  $  - AdminCensusController.php
 *
 * 作者：{{AUTO GENERATE}}
 */

//此文件使用程序自动生成，下次生成时【不会】覆盖。
//在这里可以补充、完善你的程序逻辑

namespace modules\levs\modules\ipban\controllers;

use Lev;
use lev\base\Viewv;
use modules\levs\modules\ipban\controllers\_gen\BaseAdminCensus;
use modules\levs\modules\ipban\ipRecordCacheHelper;
use modules\levs\modules\ipban\table\recordModelHelper;

!defined('INLEV') && exit('Access Denied LEV');

class BaseAdminCensusMiddle extends BaseAdminCensus
{

    public static function actionOnlyPagename()
    {
        $_GET['srhkey'] = 1;
        $_GET['isSrhkeyup'] = 1;
        static::$srhkeyWhere = "pagetotal>0";
        static::$srhtitle = 'IP';
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

    public static function actionOnlyIp()
    {
        $_GET['srhkey'] = 1;
        $_GET['isSrhkeyup'] = 1;
        static::$srhkeyWhere = "iptotal>0";
        static::$srhtitle = '页面标识';
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

    public static function headerHtm()
    {
        //return parent::headerHtm(); // TODO: Change the autogenerated stub
        //return '<tips class="gray inblk scale8">自定义headerHtm：文件位置：'.__DIR__ . '/AdminCensusController.php'.'</tips>';
        $totals = ipRecordCacheHelper::setTotalIp();
        $todIp = $totals[$Ymd = date("Ymd", Lev::$app['timestamp'])]['ip0'].'/'.$totals[$Ymd]['ip2'];
        $ysdIp = $totals[$ysd = date("Ymd", Lev::$app['timestamp']-3600*24)]['ip0'].'/'.$totals[$ysd]['ip2'];
        $Ymds = ipRecordCacheHelper::getYearsDay();
        return Viewv::renderPartial(static::$tmpPath . '/myself/headerHtm', [
            'Ymds' => $Ymds,
            'totals' => $totals,
            'todIp' => $todIp,
            'ysdIp' => $ysdIp,
        ]);
    }

    public static function footerHtm()
    {
        return parent::footerHtm(); // TODO: Change the autogenerated stub
        //return '<tips class="gray inblk scale8">自定义footerHtm</tips>';
    }

    public static function cardFooterButtons($btns = [])
    {
        return parent::cardFooterButtons($btns); // TODO: Change the autogenerated stub
        //return '<tips class="gray inblk scale8">自定义cardFooterButtons</tips>';
    }

    public static function headerViewHtm()
    {
        return parent::headerViewHtm(); // TODO: Change the autogenerated stub
        //return '<tips class="gray inblk scale8">自定义headerViewHtm：文件位置：'.__DIR__ . '/AdminCensusController.php'.'</tips>';
    }

    public static function footerViewHtm()
    {
        return parent::footerViewHtm(); // TODO: Change the autogenerated stub
        //return '<tips class="gray inblk scale8">自定义footerViewHtm</tips>';
    }

    public static function col_status() {
        return recordModelHelper::statuses();
    }

}

class AdminCensusController extends BaseAdminCensusMiddle
{

    public static $tmpPath = 'admin-census';
    public static $trash   = true;//是否允许删除数据
    public static $addurl  = false;//是否显示创建数据按钮
    public static $addRoute = 'Form_ipban_record_census';//自定义创建数据表单地址 - 默认使用源表单

    public static $srhtitle    = '';//模糊搜索字段名称
    public static $srhkeyWhere = '';//模糊搜索sql语句 例：name LIKE '%{srhkey}%'

    public static $limit = 50;//每页显示多少条
    public static $order = ['addtime DESC'];//排序

    /**
     * 列表显示字段设置
     * 例：array(
    'id'           => array('order' => null, 'name' => 'Id', 'thattr' => 'wd30 nowrap', 'merge' => []),

    'name'         => array('order' => null, 'name' => '模块名称', 'thattr' => 'wd30 nowrap', 'merge' => ['addtime']),

    'displayorder' => array('order' => null, 'name' => '排序', 'thattr' => 'wd30 nowrap', 'merge' => []),

    'uptime'       => array('order' => null, 'name' => '更新时间', 'thattr' => 'wd30 nowrap', 'merge' => []),

    );
     *
     * order: 点击字段排序
     * name: 字段名称
     * thattr: 表格th属性，放class属性内，内容举例：wd30 nowrap" style="font-size:12px
     * merge: 合并显示，多个字段合并显示到一个上
     *
     * @see BaseAdminCensus::showColumns();
     */
    public static function showColumns() {
        //return parent::showColumns(); // TODO: Change the autogenerated stub
        return array(
                'id'         => array('order' => null, 'name' => 'Id', 'thattr' => 'wd30 nowrap', 'merge' => []),

                'pagename'   => array('order' => null, 'name' => '页面标识', 'thattr' => 'wd30 nowrap', 'merge' => []),

                'ip'         => array('order' => null, 'name' => 'IP', 'thattr' => 'wd30 nowrap', 'merge' => []),

                'iptotal'    => array('order' => 1, 'name' => 'IP计数', 'thattr' => 'wd30 nowrap', 'merge' => []),

                'pagetotal'  => array('order' => 1, 'name' => 'page计数', 'thattr' => 'wd30 nowrap', 'merge' => []),

                //'requesturi' => array('order' => null, 'name' => '请求地址', 'thattr' => 'wd30 nowrap', 'merge' => []),

                //'referer'    => array('order' => null, 'name' => 'Referer', 'thattr' => 'wd30 nowrap', 'merge' => []),

                //'useragent'  => array('order' => null, 'name' => '用户标识', 'thattr' => 'wd30 nowrap', 'merge' => []),

                //'settings'   => array('order' => null, 'name' => '通用设置', 'thattr' => 'wd30 nowrap', 'merge' => []),

                'status'     => array('order' => null, 'name' => '状态', 'thattr' => 'wd30 nowrap', 'merge' => []),

                //'uptime'     => array('order' => null, 'name' => '更新时间', 'thattr' => 'wd30 nowrap', 'merge' => []),

                'addtime'    => array('order' => 1, 'name' => '添加时间', 'thattr' => 'wd30 nowrap', 'merge' => []),

            );
    }

    /**
     *
     return [
        'showtype' => [
            //从上往下先到先得
            'input_{columnKey}'  => ['width'=>120,'textarea'=>1],//显示为无刷新更改字段
            'srhkey_{columnKey}' => ['or'=>['{columnKey}']],//显示为点击可搜索字段
            'status_{columnKey}' => 1,//显示为开关状态字段 status 自动
            'order_{columnKey}'  => 1,//显示为可排序输入框 含order关键字 自动
            'time_{columnKey}'   => 1,//显示为时间格式字段 含time关键字 自动
        ],
    ];
     *
     * @return array
     */
    public static function setColumnShowtype()
    {
        //return parent::setColumnShowtype(); // TODO: Change the autogenerated stub
        return [
            'showtype' => [
                //从上往下先到先得
                'input_{columnKey}'  => ['width'=>120,'textarea'=>1],//显示为无刷新更改字段
                'srhkey_{columnKey}' => ['or'=>['{columnKey}']],//显示为点击可搜索字段
                'srhkey_addtime' => [],//显示为点击可搜索字段
                'srhkey_status' => [],//显示为点击可搜索字段
                'srhkey_ip' => [],//显示为点击可搜索字段
                'status_{columnKey}' => 1,//显示为开关状态字段 status 自动
                'order_{columnKey}'  => 1,//显示为可排序输入框 含order关键字 自动
                'time_{columnKey}'   => 1,//显示为时间格式字段 含time关键字 自动
            ],
        ];
    }

    public static function formatListsv($sv, $lists)
    {
        $v = $sv;
        $sv = parent::formatListsv($sv, $lists); // TODO: Change the autogenerated stub
        $sv['ip'] && $sv['ip'].= '<p class="scale8 transl buttons-row"><a class="button button-fill button-small" href="'.Lev::toReRoute(['admin-record', 'ip'=>$v['ip']]).'">查看访问页面</a>
                                    <a class="button-fill button color-gray button-small" target="_blank" _bk="1" href="https://www.baidu.com/baidu?wd='.$v['ip'].'">
                                    查IP
                                    </a></p>';
        $sv['pagename'] && $sv['pagename'].= '<p class="scale8 transl"><a href="'.Lev::toReRoute(['admin-record', 'pagename'=>$v['pagename']]).'">查看访问IP</a></p>';
        return $sv;
    }

    public static function formatUid($sv, $lists, $srhkey = ['uid'])
    {
        return parent::formatUid($sv, $lists, $srhkey); // TODO: Change the autogenerated stub
    }

    public static function redirct($columnKey, $sv)
    {
        return parent::redirct($columnKey, $sv); // TODO: Change the autogenerated stub
    }

    public static function optButtons($sv)
    {
        return parent::optButtons($sv); // TODO: Change the autogenerated stub
    }

    public static function footerBtns($btns = [])
    {
        return parent::footerBtns($btns); // TODO: Change the autogenerated stub
    }

}