<?php
/* 
 * Copyright (c) 2018-2021   All rights reserved.
 * 
 * 创建时间：2021-05-23 09:55
 *
 * 项目：upload  -  $  - levmodules.php
 *
 * 作者：liwei 
 */

namespace modules\levs\modules\rewrite;

use Lev;

!defined('INLEV') && exit('Access Denied LEV');

class rewriteHelper extends \lev\base\Modulesv
{

    public static $mud = [
        'version' => '1.0.211108',
    ];

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //Assetsv::registerApp(static::$mud['version']);

    }

    public static function ngnixRewriteFile() {
        return __DIR__ . '/migrations/conf/ngnix.conf';
    }

    public static function apacheRewriteFile() {
        return __DIR__ . '/migrations/conf/.htaccess';
    }

    public static function iisRewriteFile() {
        return __DIR__ . '/migrations/conf/web.config';
    }

    public static function levsRewriteFile() {
        return __DIR__ . '/migrations/conf/'.(empty(Lev::$app['isDiscuz']) ? 'levs_rewrite.php' : 'levs_rewrite_discuz.php');
    }
    /**
     * 使用密钥访问后台
     * @return string
     *
     * @see Adminv::apiCheck()
     */
    public static function adminPwd() {
//        if (urldecode(Lev::GPv('r')) != 'form-upload-zips/api') {
//            return false;
//        }
        return Lev::stget('adminPwd', 'rewrite');
    }
}