<?php
/* 
 * Copyright (c) 2018-2021   All rights reserved.
 * 
 * 创建时间：2021-05-23 09:55
 *
 * 项目：upload  -  $  - levmodules.php
 *
 * 作者：liwei 
 */

namespace modules\levs\modules\ipban;

use Lev;

!defined('INLEV') && exit('Access Denied LEV');

class ipbanHelper extends \lev\base\Modulesv
{

    public static $mud = [
        'version' => '1.0.210919',
    ];

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //Assetsv::registerApp(static::$mud['version']);

    }


    public static function getIpBanCode() {
        $filename   = 'levs_ip_ban.php';
        $ipbancode  = 'if (is_file($_levs_ip_ban_file = __DIR__ .\'/'.$filename.'\')) require $_levs_ip_ban_file;';
        $ipbancode2 = 'if (is_file($_levs_ip_ban_file = dirname(__DIR__) .\'/'.$filename.'\')) require $_levs_ip_ban_file;';
        return [
            'filename' => $filename,
            'ipbancode' => $ipbancode,
            'ipbancode2' => $ipbancode2,
        ];
    }

    public static function getRequireFile($rootSrc) {
        $codes = static::getIpBanCode();
        return is_file(dirname($rootSrc).'/'.$codes['filename']) ? $codes['ipbancode'] : $codes['ipbancode2'];
    }

    public static function checkSeted($rootSrc) {
        $codes = static::getIpBanCode();
        $data = file_get_contents($rootSrc);
        if (strpos($data, $codes['ipbancode']) !== false || strpos($data, $codes['ipbancode2']) !== false) {
            return true;//已设置
        }
        return false;
    }
}