<?php
/* 
 * Copyright (c) 2018-2021   All rights reserved.
 *
 * 创建时间：2021-12-04 11:36:26
 *
 * 项目：/levs  -  $  - BaseLevModulesModel.php
 *
 * 作者：{{AUTO GENERATE}}
 */

//此文件使用程序自动生成，下次生成时会覆盖，不建议修改。

namespace modules\levs\table\lev_modules;

use Lev;
use lev\base\Modelv;
use lev\base\SubModelv;

!defined('INLEV') && exit('Access Denied LEV');


class BaseLevModulesModel extends SubModelv
{

    public static $tableName = '{{%lev_modules}}';

    public static function safeColumnsGen($columns)
    {
        $allColumns = static::allColumns();
        if (is_array($allColumns)) {
            foreach ($columns as $field => $value) {
                if (!isset($allColumns[$field])) unset($columns[$field]);
            }
        }
        return parent::safeColumnsGen($columns); // TODO: Change the autogenerated stub
    }

    public static function allColumns() {
        return array(
                'id'           => 'Id',

                'typeid'       => '分类',

                'name'         => '模块名称',

                'identifier'   => '唯一标识',

                'classdir'     => 'Classdir',

                'descs'        => '简短描述',

                'copyright'    => '版权',

                'version'      => '版本号',

                'versiontime'  => '版本时间号',

                'settings'     => '通用设置',

                'displayorder' => '排序',

                'status'       => '状态',

                'uptime'       => '更新时间',

                'addtime'      => '添加时间',

        );
    }

    public static function inputs($iden = '', $keyfield = '', $classify = null)
    {
        //return parent::inputs($iden, $keyfield, $classify); // TODO: Change the autogenerated stub
        return array(

            'id' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => 'Id',
                    'placeholder'      => '',
                    'inputname'        => 'id',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'typeid' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '分类',
                    'placeholder'      => '',
                    'inputname'        => 'typeid',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'name' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '模块名称',
                    'placeholder'      => '',
                    'inputname'        => 'name',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'identifier' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '唯一标识',
                    'placeholder'      => '',
                    'inputname'        => 'identifier',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'classdir' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => 'Classdir',
                    'placeholder'      => '',
                    'inputname'        => 'classdir',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'descs' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '简短描述',
                    'placeholder'      => '',
                    'inputname'        => 'descs',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'copyright' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '版权',
                    'placeholder'      => '',
                    'inputname'        => 'copyright',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'version' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '版本号',
                    'placeholder'      => '',
                    'inputname'        => 'version',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'versiontime' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '版本时间号',
                    'placeholder'      => '',
                    'inputname'        => 'versiontime',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'settings' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '通用设置',
                    'placeholder'      => '<tips>【提示】序列化字段不了解情况下不要修改，否则会导致整个字段数据丢失</tips>',
                    'inputname'        => 'settings',
                    'inputtype'        => 'textarea',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'displayorder' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '排序',
                    'placeholder'      => '',
                    'inputname'        => 'displayorder',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'status' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '状态',
                    'placeholder'      => '',
                    'inputname'        => 'status',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'uptime' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '更新时间',
                    'placeholder'      => '',
                    'inputname'        => 'uptime',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
            'addtime' => array (
                    'moduleidentifier' => 'levs',
                    'classify'         => '',
                    'title'            => '添加时间',
                    'placeholder'      => '',
                    'inputname'        => 'addtime',
                    'inputtype'        => 'text',
                    'inputvalue'       => '',
                    'settings'         => '',
                    'displayorder'     => '0',
                    'status'           => '0',
            ),
        );
    }

    public static function setupDesc()
    {
        //return parent::setupDesc(); // TODO: Change the autogenerated stub
        return [];//"{{setupDesc}}";
    }

    public static function getNextSetup()
    {
        return parent::getNextSetup(); // TODO: Change the autogenerated stub
    }

    public static function inputsSetup()
    {
        return parent::inputsSetup(); // TODO: Change the autogenerated stub
    }

    /**
     * 额外的表单字段，不会存入数据库
     * @return array inputs
     */
    public static function extInputs() {
        return [];
    }

    //eg: <div class="card card-header"></div>
    /**
     * 表单头部htm
     * @return string
     */
    public static function headerHtm() {
        return !Lev::isDeveloper(Lev::$app['iden']) ? '' :
            '<tips class="gray inblk scale8">自定义headerHtm：文件位置：'.__DIR__ . '/levModulesModelHelper.php'.'</tips>';
    }

    /**
     * 表单底部htm
     * <tips class="gray inblk scale8">自定义footerHtm</tips>
     * @return string
     */
    public static function footerHtm() {
        return '';
    }

    /**
     * 表单底部内部htm
     * <tips class="gray inblk scale8">自定义footerFormInnerHtm</tips>
     * @return string
     */
    public static function footerFormInnerHtm() {
        return '';
    }

}