<?php
/* 
 * Copyright (c) 2018-2021   All rights reserved.
 * 
 * 创建时间：2021-05-23 09:55
 *
 * 项目：upload  -  $  - levmodules.php
 *
 * 作者：liwei 
 */

namespace modules\levs\modules\composer;

use Lev;
use lev\base\Assetsv;

!defined('INLEV') && exit('Access Denied LEV');

class composerHelper extends \lev\base\Modulesv
{

    public static $mud = [
        'version' => '1.0.211227',
    ];

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //Assetsv::registerApp(static::$mud['version']);

    }

    public static function assets() {
        return Assetsv::getAppassets('composer');
    }

    public static function assetsRoot() {
        return Assetsv::getAppAssetsRoot('composer');
    }

    /**
     * 使用密钥访问后台
     * @return string
     *
     * @see Adminv::apiCheck()
     */
    public static function adminPwd() {
//        if (urldecode(Lev::GPv('r')) != 'form-upload-zips/api') {
//            return false;
//        }
        return Lev::stget('adminPwd', 'composer');
    }
}